[workspace]
resolver = "2"
members = ["oxidegl", "xtask"]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[profile.dev]
codegen-units = 512
incremental = true
lto = "thin"
panic = "abort"
