[workspace]
resolver = "2"
members = ["oxidegl", "xtask"]

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
debug = true

[profile.dev]
codegen-units = 512
# lto = "thin"
panic = "abort"
incremental = true
