[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86" }
clap = { version = "4.5.7", features = ["derive"] }
const_format = "0.2.32"
dashmap = "6.0.1"
enum_dispatch = "0.3.13"
roxmltree = "0.20.0"
strum_macros = "0.26.3"
